name: concurrency-16-multi-jobset-same-gate
on: workflow_dispatch
jobs:
  call-1:
    uses: ./.github/workflows/reusable-callee-concurrency.yml
    with:
      val: "multi-jobset"
      concurrency_group: "shared-embedded-16"
  call-2:
    uses: ./.github/workflows/reusable-callee-concurrency.yml
    with:
      val: "multi-jobset"
      concurrency_group: "shared-embedded-16"
  call-3:
    uses: ./.github/workflows/reusable-callee-concurrency.yml
    with:
      val: "multi-jobset"
      concurrency_group: "shared-embedded-16"
